# Generated by Django 2.0.2 on 2018-02-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('concert', 'Konzert'), ('service', 'Gottesdienst'), ('prayer', 'Andacht'), ('hidden', 'Nichtöffentliche Veranstaltung'), ('default', 'Sonstige Veranstaltung')], default='default', help_text='Gottesdienste und Konzerte werden auf den besonderen Seite zusätzlich angezeigt.', max_length=255, verbose_name='Veranstaltungstyp')),
                ('title', models.CharField(help_text='Kurzer Titel der Veranstaltung', max_length=255, verbose_name='Titel')),
                ('content', models.TextField(blank=True, help_text='Beschreibung der Veranstaltung.', verbose_name='Inhalt')),
                ('begin', models.DateTimeField(verbose_name='Beginn')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Wenn nichts angegeben ist, wird keine Zeit für das Ende der Veranstaltung angezeigt.', null=True, verbose_name='Dauer in Minuten')),
                ('on_home_before_begin', models.PositiveIntegerField(default=0, help_text='Die Veranstaltung erscheint so viele Tage vor Beginn auf der Startseite. Wählen Sie 0, wenn die Veranstaltung niemals auf der Startseite erscheinen soll. Der nächste Gottesdienste und das nächste Konzert erscheinen immer auf der Startseite, egal, was hier eingestellt ist.', verbose_name='Auf der Startseite (in Tagen)')),
            ],
            options={
                'verbose_name_plural': 'Veranstaltungen',
                'ordering': ('begin',),
                'verbose_name': 'Veranstaltung',
                'permissions': (('can_see_hidden_events', 'Darf nichtöffentliche Veranstaltungen sehen'),),
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediafile', models.FileField(help_text='Achtung: Hochgeladene Dateien sind für jeden im Internet sichtbar.', max_length=255, upload_to='', verbose_name='Datei')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
            ],
            options={
                'verbose_name_plural': 'Dateien',
                'ordering': ('-uploaded_on',),
                'verbose_name': 'Datei',
            },
        ),
    ]
