# Generated by Django 2.0.2 on 2018-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('concert', 'Konzert'), ('period-of-reflection', 'Rüstzeit'), ('service', 'Gottesdienst'), ('hidden', 'Nichtöffentliche Veranstaltung'), ('default', 'Sonstige Veranstaltung'), ('prayer', 'Andacht'), ('gathering', 'Treff')], default='default', help_text='Gottesdienste und Konzerte werden auf den besonderen Seite zusätzlich angezeigt.', max_length=255, verbose_name='Veranstaltungstyp'),
        ),
    ]
