# Generated by Django 2.0.2 on 2018-04-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0002_auto_20180312_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('default', 'Sonstige Veranstaltung'), ('concert', 'Konzert'), ('period-of-reflection', 'Rüstzeit'), ('gathering', 'Treff'), ('service', 'Gottesdienst'), ('prayer', 'Andacht'), ('hidden', 'Nichtöffentliche Veranstaltung')], default='default', help_text='Gottesdienste und Konzerte werden auf den besonderen Seite zusätzlich angezeigt.', max_length=255, verbose_name='Veranstaltungstyp'),
        ),
    ]
