# Generated by Django 2.0.6 on 2018-07-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dreifaltigkeit", "0003_flatpage_menu_title")]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dreifaltigkeit.MediaFile",
                verbose_name="Bild",
            ),
        )
    ]
