# Generated by Django 2.0.2 on 2018-04-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0004_auto_20180411_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, help_text='Ort der Veranstaltung, z. B. Trinitatiskirche, Markuskapelle, Anbau der Trinitatiskirche, Gemeindehaus Dresdner Straße 59', max_length=255, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, default='Trinitatiskirche', help_text='Ort der Veranstaltung, z. B. Trinitatiskirche, Markuskapelle, Anbau der Trinitatiskirche, Gemeindehaus Dresdner Straße 59', max_length=255, verbose_name='Ort'),
        ),
    ]
