# Generated by Django 2.2 on 2019-09-09 22:29

from django.conf import settings
from django.db import migrations


def change_flat_page(apps, schema_editor):
    """
    Changes one parish flat page.
    """
    if settings.SITE_ID == 'parish':
        # We can't import the model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        FlatPage = apps.get_model('dreifaltigkeit', 'FlatPage')

        flat_page_1 = FlatPage.objects.get(category='parish_root', url='spenden')
        flat_page_1.title = 'Spenden und Kirchgeld'
        flat_page_1.menu_title = 'Spenden · Kirchgeld'
        flat_page_1.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0005_mediafile_text'),
    ]

    operations = [
        migrations.RunPython(change_flat_page),
    ]
