# Generated by Django 2.0.2 on 2018-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0005_event_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kurzer Titel der Ankündigung', max_length=255, verbose_name='Titel')),
                ('short_text', models.TextField(help_text='Kurzer Text, erscheint auf der Startseite.', verbose_name='Kurztext')),
                ('long_text', models.TextField(blank=True, help_text='Längerer Text. Erscheint auf einer gesonderten Seite, die von der Startseite aus erreichbar ist.', verbose_name='Text')),
                ('end', models.DateTimeField(help_text='Bis zu diesem Zeitpunkt ist die Ankündigung auf der Startseite und ggf. über den gesonderten Link erreichbar.', verbose_name='Ende')),
            ],
            options={
                'verbose_name_plural': 'Ankündigungen',
                'verbose_name': 'Ankündigung',
                'ordering': ('-end',),
            },
        ),
    ]
