# Generated by Django 2.2 on 2019-09-26 18:45

from django.conf import settings
from django.db import migrations


def change_and_add_flat_pages(apps, schema_editor):
    """
    Changes one parish flat page.
    """
    if settings.SITE_ID == "parish":
        # We can't import the model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        FlatPage = apps.get_model("dreifaltigkeit", "FlatPage")

        flat_page_1 = FlatPage.objects.get(
            category="kinder-und-jugend", url="krabbelkreis"
        )
        flat_page_1.title = "Eltern-Kind-Café (Krabbelkreis)"
        flat_page_1.save()

        FlatPage.objects.create(
            category="kinder-und-jugend",
            url="kleine-gemeindefuechse",
            title="Kleine Gemeindefüchse",
            menu_title="",
            ordering=315,
            redirect="",
        )
    elif settings.SITE_ID == "kindergarden":
        pass
    else:
        raise RuntimeError(
            "The settings variable SITE_ID has to be set. Use 'parish' or "
            "'kindergarden'."
        )


class Migration(migrations.Migration):

    dependencies = [("dreifaltigkeit", "0006_flat_page_default_data_change_again")]

    operations = [migrations.RunPython(change_and_add_flat_pages)]
