# Generated by Django 2.0.2 on 2018-04-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0006_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='long_text',
            field=models.TextField(blank=True, help_text='Längerer Text. Erscheint nur auf einer gesonderten Seite, die von der Startseite aus erreichbar ist.', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='short_text',
            field=models.TextField(help_text='Kurzer Text. Erscheint auf der Startseite.', verbose_name='Kurztext'),
        ),
    ]
