# Generated by Django 2.0.2 on 2018-04-22 19:27

from django.db import migrations, models
import dreifaltigkeit.models


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0007_auto_20180417_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Eingabe als sechsstellige Zahl bestehend aus Jahr und Monat z. B. 201307 für Juli 2013.', validators=[dreifaltigkeit.models.validate_year_month_number], verbose_name='Monat')),
                ('text', models.TextField(help_text='Der Monatsspruch erscheint nur auf der Gottesdienstseite.', verbose_name='Monatsspruch')),
                ('verse', models.CharField(help_text='Beispiel: Joh 19,30.', max_length=255, verbose_name='Bibelstelle')),
            ],
            options={
                'ordering': ('-month',),
                'verbose_name': 'Monatsspruch',
                'verbose_name_plural': 'Monatssprüche',
            },
        ),
    ]
