# Generated by Django 2.2.5 on 2019-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dreifaltigkeit", "0007_flat_page_change_krabbelkreis")]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="on_home_before_end",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Die Ankündigung erscheint so viele Tage vor ihrem Ende auf der Startseite. Die Einstellung ermöglicht eine verzögerte Veröffentlichung.",
                verbose_name="Auf der Startseite (Angabe in Tagen)",
            ),
        )
    ]
