# Generated by Django 2.0.6 on 2018-08-19 18:54

from django.conf import settings
from django.db import migrations


def change_flat_pages(apps, schema_editor):
    """
    Changes two parish flat pages.
    """
    if settings.SITE_ID == 'parish':
        # We can't import the model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        FlatPage = apps.get_model('dreifaltigkeit', 'FlatPage')

        flat_page_1 = FlatPage.objects.get(category='kirchenmusik', url='floetenkreis')
        flat_page_1.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0008_yearlytext'),
    ]

    operations = [
        migrations.RunPython(change_flat_pages),
    ]
