# Generated by Django 2.2.5 on 2020-03-15 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("dreifaltigkeit", "0008_announcement_on_home_before_end")]

    operations = [
        migrations.CreateModel(
            name="ClericalWordAudioFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Achtung: Hochgeladene Dateien sind für jeden im Internet sichtbar.",
                        max_length=255,
                        upload_to="",
                        verbose_name="Audio-Datei",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Kurzer Titel des Beitrags.",
                        max_length=255,
                        verbose_name="Titel",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Kein HTML erlaubt.",
                        verbose_name="Beschreibung des Beitrags",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="audio/mpeg",
                        help_text="Dieser Wert ist ggf. an das Dateiformat anzupassen (z. B. in audio/mp4, audio/ogg, audio/wav).",
                        max_length=255,
                        verbose_name="MIME-Type (Internet Media Type)",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "pubdate",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Veröffentlicht am"
                    ),
                ),
            ],
            options={
                "verbose_name": "Geistliches Wort Audio-Datei",
                "verbose_name_plural": "Geistliches Wort Audio-Dateien",
                "ordering": ("-pubdate",),
            },
        )
    ]
