# Generated by Django 2.0.2 on 2018-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0009_auto_20180422_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gemeinde', 'Gemeinde'), ('kirchenmusik', 'Kirchenmusik'), ('kinder-und-jugend', 'Kinder und Jugend')], max_length=255, verbose_name='Kategorie')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('ordering', models.IntegerField(verbose_name='Sortierung')),
                ('content', models.TextField(blank=True, help_text='Inhalt der Seite in HTML.', verbose_name='Inhalt')),
            ],
            options={
                'verbose_name': 'Statische Seite',
                'verbose_name_plural': 'Statische Seiten',
                'ordering': ('ordering',),
            },
        ),
    ]
