# Generated by Django 2.0.2 on 2018-05-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0010_flatpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='redirect',
            field=models.CharField(blank=True, max_length=255, verbose_name='Weiterleitung'),
        ),
    ]
