# Generated by Django 2.0.6 on 2018-09-06 20:22

from django.conf import settings
from django.db import migrations


def change_flat_pages(apps, schema_editor):
    """
    Changes one parish flat page.
    """
    if settings.SITE_ID == 'parish':
        # We can't import the model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        FlatPage = apps.get_model('dreifaltigkeit', 'FlatPage')

        flat_page_1 = FlatPage.objects.get(category='kinder-und-jugend', url='kirche-fuer-kids')
        flat_page_1.title = 'Kirche für Kids (Christenlehre)'
        flat_page_1.menu_title = 'Kirche für Kids (Christenlehre)'
        flat_page_1.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0010_auto_20180830_2205'),
    ]

    operations = [
        migrations.RunPython(change_flat_pages),
    ]
