# Generated by Django 2.2.5 on 2020-03-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0010_flat_page_default_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='long_text',
            field=models.TextField(blank=True, help_text='Längerer Text. Erscheint nur auf einer gesonderten Seite, die von der Startseite aus erreichbar ist. Kein HTML erlaubt. Leerzeilen können verwendet werden. Links im Markdown-Stil sind möglich, d. h. [Text](URL).', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='short_text',
            field=models.TextField(help_text='Kurzer Text. Erscheint auf der Startseite. Kein HTML erlaubt. Links im Markdown-Stil sind möglich, d. h. [Text](URL).', verbose_name='Kurztext'),
        ),
    ]
