# Generated by Django 2.2.5 on 2020-03-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dreifaltigkeit", "0011_auto_20200320_2120")]

    operations = [
        migrations.AddField(
            model_name="clericalwordaudiofile",
            name="mediafile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dreifaltigkeit.MediaFile",
                verbose_name="Bild",
            ),
        )
    ]
