# Generated by Django 4.1.7 on 2024-02-23 16:23

from django.conf import settings
from django.db import migrations


def add_flat_page(apps, schema_editor):
    """
    Add one parish flat page.
    """
    if settings.SITE_ID == "parish":
        # We can't import the model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        FlatPage = apps.get_model("dreifaltigkeit", "FlatPage")

        FlatPage.objects.create(
            category="kinder-und-jugend",
            url="familienkirche",
            title="Familienkirche",
            menu_title="Familienkirche",
            ordering=335,
            redirect="",
        )
    elif settings.SITE_ID == "kindergarden":
        pass
    else:
        raise RuntimeError(
            "The settings variable SITE_ID has to be set. Use 'parish' or "
            "'kindergarden'."
        )

class Migration(migrations.Migration):

    dependencies = [
        ('dreifaltigkeit', '0017_flat_page_change_christenlehre_20221104_2030'),
    ]

    operations = [migrations.RunPython(add_flat_page)]
