# Generated by Django 4.1.7 on 2025-12-30 12:56

from django.conf import settings
from django.db import migrations


def remove_flat_page(apps, schema_editor):
    """
    Remove one parish flat page.
    """
    if settings.SITE_ID == "parish":
        # We can't import the model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        FlatPage = apps.get_model("dreifaltigkeit", "FlatPage")

        FlatPage.objects.get(category="kinder-und-jugend", url="kleine-gemeindefuechse").delete()
    elif settings.SITE_ID == "kindergarden":
        pass
    else:
        raise RuntimeError(
            "The settings variable SITE_ID has to be set. Use 'parish' or "
            "'kindergarden'."
        )

class Migration(migrations.Migration):

    dependencies = [
        ("dreifaltigkeit", "0020_flat_page_add_ruestzeiten"),
    ]

    operations = [migrations.RunPython(remove_flat_page)]
