# Generated by Django 4.1.7 on 2026-05-22 11:05

from django.conf import settings
from django.db import migrations

def add_flat_page(apps, schema_editor):
    """
    Add one flat page.
    """
    if settings.SITE_ID == "kindergarden":
        # We can't import the model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        FlatPage = apps.get_model("dreifaltigkeit", "FlatPage")

        FlatPage.objects.create(
            category="kindergarden_root",
            url="galerie",
            title="Galerie",
            menu_title="Galerie",
            ordering=125,
            redirect="",
        )
    elif settings.SITE_ID == "parish":
        pass
    else:
        raise RuntimeError(
            "The settings variable SITE_ID has to be set. Use 'parish' or "
            "'kindergarden'."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("dreifaltigkeit", "0023_flat_page_kinder_im_godi"),
    ]

    operations = [migrations.RunPython(add_flat_page)]
